{% set name = "pyweed" %}
{% set version = "1.0.1a1" %}
{% set sha256 = "2a0e1e12e59e48447a01ccfc88f400edc1af71a3938862a82de7d4d50fbe3c4c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]
  entry_points:
    - pyweed = pyweed.pyweed_launcher:launch

requirements:
  host:
    - python
    - setuptools
  run:
    - python 3.6*
    - basemap
    - future
    - matplotlib 2*
    - obspy 1.1*
    - pandas
    - pillow
    - pyqt 4.11*
    - qtconsole
    - pyzmq
    - pyproj
    - proj4


test:
  imports:
    - pyweed
  commands:
    - python -m pyweed.tests

about:
  home: https://iris-edu.github.io/pyweed/
  dev_url: https://github.com/iris-edu/pyweed
  license: LGPL-3.0
  license_file: LICENSE
  summary: "PyWEED: A cross-platform app for retrieving event-based seismic data."

extra:
  recipe-maintainers:
    - adam-iris
