{% set name = "pyweed" %}
{% set version = "1.0.12" %}
{% set build_number = 0 %}
{% set sha256 = "7f2e057f3a014d16492373d6cbee1d49d0f917f8a92a86cce97fc3098c4312b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: pip install .
  number: {{ build_number }}
  skip: true  # [py>=312]
  entry_points:
    - pyweed = pyweed.pyweed_launcher:launch

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - basemap <1.5
    - matplotlib-base
    - obspy <1.4
    - pillow
    - pyqt <6
    - pyproj


test:
  imports:
    - pyweed
  commands:
    - python -m pyweed.tests

about:
  home: https://iris-edu.github.io/pyweed/
  dev_url: https://github.com/iris-edu/pyweed
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: "PyWEED: A cross-platform app for retrieving event-based seismic data."

extra:
  recipe-maintainers:
    - adam-iris
