appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: y2y0Mj/gjz46wsP5hDm5M5ONAg219wKaielxX/4Y0KgHWZjK3fcxSSa9wIaI7TM0HebeBCJKev4i8iXlSzYLe+HsoZl5ZwJkPizDGMuCxviSktPsMhxfcIxGhY4fOfI9DgavJ9M7OIPV417Gqp1E2O/4A5Bl3R/Mi3BFDfdEJQ5KOaVLScNzlRvJtv2ciR6ah5Q3NrJr8aRyi96PjokdqzIq8ETEryBgc/s6noB7iokucY6B79y+CbApesZN8taaQfNwo2yFa7Z5bKF9ht8LHlY98aCC4YEWsWgAW5fuujoRYS0qiehhQ6/NspgVUqe+zoHxCUgmGPwkxlG5Pb1iBtWXyY8DPSSASnzWSHWw8IaBcVC80MJBW2CrevfeocuH6li+SCHFu2kpRd71oExqyKWuvVOZJDkvjn/ReooZAFvzuKIXjX2Sh/81UQxOhyaoU6Ut3ftZhpn8iaHzRiX1XEqSRG0R8xWAb2os+2RyzeTNAsV6H5h8jNE3WGW3JwEPT5hUlerpLv1IovHq1Jp0O5s0Mkv9Iy1DPZxh78A8foEmpI30uVQKDlXhUXb8RNhNkhA8aGNrt+sG6kcj67flggJaf+ZGoG2zvukIJ+X9CUZQdy3InHxyguprr9LEn/7uaB6cy75ZiMX30koFTRQl51BGR/GoxcaeDRcd7gGq+lw=}
provider:
  win: azure
conda_forge_output_validation: true
